POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "GrateTastes_12345",
  "password": "everest1999"
}

###
GET http://localhost:8080/profile
Accept: application/json
Cookie: session_id=PMv0kUiQmQa3YjBuLaSSTjpY9CeukaQMdL2sODB7K0JRM7CrKvXbJA==;

###
POST http://localhost:8080/auth/signup
Content-Type: application/json
Origin: http://127.0.0.1:8081


{
  "username": "tester",
  "email": "email@mail.l",
  "password": "password123"
}

###

PUT http://localhost:8080/profile/edit
Origin: http://localhost:8081
Cookie: session_id=-0Ley-BzPT9nFGDtHOqy9hzspuqB1dLsfsOlS79lcWzEWdiQKjclJA==;
Content-Type: application/json

{
  "email": "email@mail.l"
}


###

#  boards: {
#    createBoard: 'create-board',
#    deleteBoard: 'delete-board',
#    loadBoardsFeed: 'load-boards-feed',
#  },
#  profiles: {
#    follow: 'follow',
#    unfollow: 'unfollow',
#  },
#  messages: {
#    comment: 'comment-left',
#    read: 'message-read',
#  },
#  common: {
#    loadForeignProfile: 'load-profile',
#    loadPin: 'load-pin', // load pin for pin's page. It contains messages, author's profile and so on
#    loadBoard: 'load-board',
#  },
