#!/bin/bash

STAGED_JS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")

if [[ "$STAGED_JS_FILES" = "" ]]; then
  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n\n"
  exit 0
fi

printf "pre-commit hook started...\n"
PASS=true
printf "Validating JS:\n\n"

for FILE in $STAGED_JS_FILES
do
  if npx -s eslint "$FILE"; then
    printf "\t\033[32mESLint Passed: %s\033[0m" "$FILE"
  else
    printf "\t\033[41mESLint Failed: %s\033[0m" "$FILE"
    PASS=false
  fi
done

printf "\n\nJS validation done.\n\n"

if ! $PASS; then
  printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  printf "\033[42mCOMMIT SUCCEEDED\033[0m\n\n"
  exit 0
fi
